AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  edesoft-lamda

  Sample SAM Template for edesoft-lamda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  DataProcessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: data_processor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          DB_CONNECTION_STRING: postgresql://<user>:<psd>@<host>:5432
          AWS_ACCESS: <ACCESS>
          AWS_SECRET: <SECRET>
      Events:
        UploadCsvEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
        DataProcessor:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /process
            Method: get
  SrcBucket:
    Type: AWS::S3::Bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DataProcessorApi:
    Description: "API Gateway endpoint URL for Prod stage for Data Processor function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/process/"
  DataProcessorFunction:
    Description: "Data Processor Lambda Function ARN"
    Value: !GetAtt DataProcessorFunction.Arn
  DataProcessorFunctionIamRole:
    Description: "Implicit IAM Role created for Data Processor function"
    Value: !GetAtt DataProcessorFunctionRole.Arn
